leica-m6:
  brand: Leica
  model: m6
  format: 135
nikonos-v:
  brand: Nikon
  model: nikonos V
  format: 135
olympus-xa:
  brand: Olympus
  model: XA
  format: 135
lubitel-166:
  brand: Lubitel
  model: 166b
  format: 120
canonet:
  brand: Canon
  model: Canonet
  format: 135
lca-plus:
  brand: Lomography
  model: LCA +
  format: 135
