ultramax:
  brand: Kodak
  name: Ultramax
  color: true
  iso: 400
  formats:
    - 135
portra-400:
  brand: Kodak
  name: Portra
  color: true
  iso: 400
  formats:
    - 135
    - 120
gold-200:
  brand: Kodak
  name: Gold
  color: true
  iso: 200
  formats:
    - 135
lomo-400:
  brand: Lomography
  name: Color Negative
  color: true
  iso: 400
  formats:
    - 135
    - 120
xpro-200:
  brand: Lomography
  name: X-pro
  color: true
  iso: 200
  formats:
    - 135
portra-800:
  brand: Kodak
  name: Portra
  color: true
  iso: 800
  formats:
    - 135
    - 120
trix-400:
  brand: Kodak
  name: tri-x
  color: false
  iso: 400
  formats:
    - 135
    - 120
kiro-400:
  brand: Film never die
  name: Kiro
  color: true
  iso: 400
  formats:
    - 135
ilford-hp5:
  brand: Ilford
  name: HP5
  color: false
  iso: 400
  formats:
    - 135
redscale-50:
  brand: Lomography
  name: redscale
  color: true
  iso: 50
  formats:
    - 120
unknown:
  brand: Unknown
  name: film
sensia-50:
  brand: Fuji
  name: Sensia
  color: true
  iso: 50
  formats:
    - 135
