portra-400:
  name: Kodak Portra
  color: true
  iso: 400
  formats:
    - 135
    - 120
gold-200:
  name: Kodak Gold
  color: true
  iso: 200
  formats:
    - 135
lomo-400:
  name: Lomography Color Negative
  color: true
  iso: 400
  formats:
    - 135
    - 120
xpro-200:
  name: Lomography X-pro
  color: true
  iso: 200
  formats:
    - 135
portra-800:
  name: Kodak Portra
  color: true
  iso: 800
  formats:
    - 135
    - 120
trix-400:
  name: Kodak tri-x
  color: false
  iso: 400
  formats:
    - 135
    - 120
kiro-400:
  name: Film never die Kiro
  color: true
  iso: 400
  formats:
    - 135
ilford-hp5:
  name: Ilford HP5
  color: false
  iso: 400
  formats:
    - 135
redscale-50:
  name: lomography redscale
  color: true
  iso: 50
  formats:
    - 120
unknown:
  name: Unknown
sensia-50:
  name: Fuji Sensia
  color: true
  iso: 50
  formats:
    - 135
